### 1. Criar um utilizador de teste para o frontend
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Utilizador de Teste",
  "email": "teste@orquestra.com",
  "password": "123456"
}

###
### 2. Autenticar (fazer login) para pegar o TOKEN
POST http://localhost:3333/sessions
Content-Type: application/json

### 5. Buscar um quadro específico e as suas tarefas
GET http://localhost:3333/boards/ID_DO_QUADRO_AQUI
Authorization: Bearer 